In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris() #导入鸢尾花的数据
iris.keys() #获取数据内容

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [3]:
X = iris.data  #鸢尾花的特征向量
y = iris.target  #鸢尾花的类别

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

## train_test_split

In [6]:
y #类别都是按顺序排列的，对于测试数据而言，有各种类别才能更准确地体现算法效果

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffled_indexes = np.random.permutation(len(X)) #打乱索引
shuffled_indexes

array([120, 117,  54,  36, 136,  69,  19, 141,  81,   8, 122,  16,  58,
        75,   0,  93,  32,  38, 114,  18,  33, 111,  20,  97, 107, 149,
       127, 145, 143,  82, 147, 144, 115, 108,  41, 105,  64,  87,  12,
        29,  67, 129,  52, 135, 134,  63,   4,  88, 125, 142, 119, 148,
       101,  68,  34, 132,  66, 106,  27,  45, 112,  51, 131,  78,  49,
        60, 146,  71,  92,  72, 103, 126,  79,  83,  30, 118,  84,  24,
        59,  61,   1,  53,  99,  95, 102,  26,  47,   2,  80,  70,  89,
        86,  62,  14,  28,  43,  35,  25, 128,  98, 116,  65,  76,   6,
         7, 133, 140,  56,   3,  23, 124,  48, 110, 100,  31,  46, 104,
       123, 109, 138,  10,  44,  57,  39,  91,  37,  22, 130,  94,  50,
        73,  77,  90,  13,  42,   9,  85,  96, 113,  17,  40, 137,  55,
         5,  11, 121,  15,  74, 139,  21])

In [9]:
test_ratio = 0.2 #测试数据的比率
test_size = int(len(X) * test_ratio) #测试数据的数量

In [10]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 使用自己封装的代码

In [16]:
from model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [19]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [20]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 测试我们的算法

In [22]:
from KNN import KNNclassifier

In [23]:
my_knn_clf = KNNclassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)
y_predict

array([0, 0, 1, 1, 1, 2, 0, 0, 0, 2, 1, 1, 2, 1, 1, 0, 0, 1, 2, 2, 2, 1,
       0, 0, 1, 2, 2, 1, 2, 1])

In [24]:
y_test

array([0, 0, 2, 1, 1, 2, 0, 0, 0, 2, 1, 1, 2, 1, 1, 0, 0, 1, 2, 1, 2, 1,
       0, 0, 1, 2, 2, 2, 2, 1])

In [25]:
sum(y_predict == y_test)

27

In [26]:
sum(y_predict == y_test) / len(y_test) #预测正确的结果/测试数据总数

0.9

## sklearn中的train_test_split

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [29]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [30]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
